// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// str_to_repair_grammar
std::unordered_map<int, std::string> str_to_repair_grammar(CharacterVector str);
RcppExport SEXP GI_str_to_repair_grammar(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type str(strSEXP);
    __result = Rcpp::wrap(str_to_repair_grammar(str));
    return __result;
END_RCPP
}
