# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs RePair algorithm on the string.
#'
#' @param str the input string.
#' @useDynLib GI
#' @export
#' @references  N.J. Larsson and A. Moffat. Offline dictionary-based compression.
#' In Data Compression Conference, 1999.
#' @examples
#' str_to_repair_grammar("abc abc cba cba bac xxx abc abc cba cba bac")
str_to_repair_grammar <- function(str) {
    .Call('GI_str_to_repair_grammar', PACKAGE = 'GI', str)
}

